---
# Ansible Playbook to upload new Cisco IOS
# Only upload file if the current IOS version is different

- name: Upload new CISCO IOS files
  hosts: "{{ device }}"
  gather_facts: no
  connection: network_cli

  vars:
    upgrade_ios_version: 17.06.04
    new_ios_file_name: cat9k_lite_iosxe.17.06.04.SPA.bin
    ansible_command_timeout: 1200
    tftp_ip_server: 148.228.8.232
    ios_hash: 656f3b02325435c69cb6dd33ee9ef684


  tasks:
    - name: CHECK CURRENT VERSION
      ios_facts:

    - debug:
        msg:
        - "Current version is {{ ansible_net_version }}"
        - "Upgrade image is {{upgrade_ios_version }}"

    - debug:
        msg:
        - "New IOS and current IOS are different."

      when: ansible_net_version != upgrade_ios_version


    - name: CLEAR FLASH TO SWITCH
      cli_command:
         command: 'install remove inactive'
         prompt: Do you want to remove the above files
         answer: 'y'
      when: ansible_net_version != upgrade_ios_version
 


    - name: COPY_NEW_IOS_FROM_FTP (172.18.124.94)
      cli_command:
         command: 'copy tftp://{{tftp_ip_server}}/{{new_ios_file_name}} flash:'
         prompt:
           - 'Destination filename \[{{ new_ios_file_name }}\]?'
         answer: '{{new_ios_file_name}}'
      when: ansible_net_version != upgrade_ios_version


    - name: Check md5sum of IOS on device
      cli_command:
        command: 'verify /md5 flash:{{ new_ios_file_name }} {{ ios_hash }}'
      register: md5_output
      when: ansible_net_version != upgrade_ios_version


    - name: Continue if hash matches
      block:

      - name: Set new boot variable
        ios_config:
          lines: boot system flash:packages.conf
          save_when: always

      - name: Write config
        ios_command:
          commands:
            - command: wr mem

      - name: Install new IOS
        ios_command:
          commands: 'install add file flash:{{ new_ios_file_name }} activate commit prompt-level none'
        vars:
          ansible_command_timeout: 1800

          #      - name: Confirmaciacon
          #        pause:
          #          prompt: Do you want to remove the above files
         
      - name: Wait for switch to reboot
        wait_for:
          host: "{{ ansible_host }}"
          port: 22
          delay: 60
          timeout: 600
        delegate_to: localhost


      when: '"Verified" in md5_output.stdout'


